Repository im85288/service.upnext, pull requests merged in 2020-03, with the labels that each got.

#175 Restore "Ignore Playlist" option
  resources/lib/playbackmanager.py
  resources/lib/script.py
  resources/settings.xml
Labels: enhancement

#178 Replace screenshots with valid alternatives
  addon.xml
  resources/media/screenshot-01.jpg
  resources/media/screenshot-02.jpg
  resources/media/screenshot-03.jpg
  resources/media/screenshot-04.jpg
  resources/media/screenshot01.jpg
  resources/media/screenshot02.jpg
  resources/media/upnext-developer.jpg
  resources/media/upnext-settings.jpg
Labels: enhancement

#177 Migrate from Travis CI to GitHub CI
  .gitattributes
  .github/workflows/addon-check.yml
  .github/workflows/ci.yml
  .travis.yml
  Makefile
  README.md
  codecov.yml
  tests/__init__.py
  tests/test_encoding.py
  tests/userdata/addon_settings.json
  tests/userdata/global_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
Labels: testing

#179 Add initial Romanian translation
  resources/language/resource.language.ro_ro/strings.po
Labels: translations
