Repository im85288/service.upnext, pull requests merged in 2020-01, with the labels that each got.

#147 Add `notification_offset` for Netflix
  resources/lib/api.py
Labels: enhancement

#133 Implement play_url support
  resources/lib/api.py
  resources/lib/playbackmanager.py
  resources/lib/utils.py
Labels: enhancement

#149 Assorted translation fixes
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.pl_pl/strings.po
Labels: release, translations

#153 Add System.Time and endtime to notification
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_JP/strings.po
  resources/language/resource.language.ko_KR/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.pl_pl/strings.po
  resources/lib/playbackmanager.py
  resources/lib/script.py
  resources/lib/stillwatching.py
  resources/lib/upnext.py
  resources/lib/utils.py
  resources/skins/default/1080i/script-upnext-stillwatching.xml
  resources/skins/default/1080i/script-upnext-upnext.xml
Labels: enhancement

#155 Update strings.po
  resources/language/resource.language.hu_hu/strings.po
Labels: translations

#152 update Croatian hr_hr #112
  resources/language/resource.language.hr_hr/strings.po
Labels: translations

#151 Translation Portuguese (Brazil)
  resources/language/resource_language_pt_br/string.spo
Labels: translations

#150 Added italian description to addon.xml
  addon.xml
Labels: translations

#156 Assorted language fixes
  resources/language/resource.language.ja_jp/strings.po
  resources/language/resource.language.ko_kr/strings.po
  resources/language/resource.language.pt_br/strings.po
Labels: translations

#161 Added swedish description to addon.xml
  addon.xml
Labels: translations

#162 Added Swedish translations
  resources/language/resource.language.sv_se/strings.po
Labels: translations

#163 Add slovak translation
  resources/language/resource.language.sk_sk/strings.po
Labels: translations

#160 Add russian translation
  addon.xml
  resources/language/resource.language.ru_ru/strings.po
Labels: translations

#165 Small fixes to existing language files
  resources/language/resource.language.es_es/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.ja_jp/strings.po
  resources/language/resource.language.pt_br/strings.po
Labels: translations

#148 Prepare for v1.1.0 release
  README.md
  addon.xml
Labels: release

#166 Do not show "Ends at:" when endtime is missing
  README.md
  addon.xml
  resources/lib/utils.py
  resources/skins/default/1080i/script-upnext-stillwatching.xml
  resources/skins/default/1080i/script-upnext-upnext.xml
Labels: bug

#167 Fix docstrings
  resources/lib/api.py
  resources/lib/monitor.py
  resources/lib/player.py
  resources/lib/script.py
  resources/lib/script_entry.py
  resources/lib/statichelper.py
  resources/lib/utils.py
Labels: enhancement
