Repository im85288/service.upnext, pull requests merged in 2020-10, with the labels that each got.

#219 Enable customAutoPlay by default and get rid of seekTime()
  resources/lib/playbackmanager.py
  resources/settings.xml
Labels: bug, enhancement

#221 Restore the conditional playnext()
  resources/lib/playbackmanager.py
Labels: bug

#220 Implement DEMO mode
  resources/language/resource.language.cs_cz/strings.po
  resources/language/resource.language.de_de/strings.po
  resources/language/resource.language.el_gr/strings.po
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.es_es/strings.po
  resources/language/resource.language.fr_fr/strings.po
  resources/language/resource.language.hr_hr/strings.po
  resources/language/resource.language.hu_hu/strings.po
  resources/language/resource.language.in_hi/strings.po
  resources/language/resource.language.it_it/strings.po
  resources/language/resource.language.ja_jp/strings.po
  resources/language/resource.language.ko_kr/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/language/resource.language.pl_pl/strings.po
  resources/language/resource.language.pt_br/strings.po
  resources/language/resource.language.ro_ro/strings.po
  resources/language/resource.language.ru_ru/strings.po
  resources/language/resource.language.sk_sk/strings.po
  resources/language/resource.language.sv_se/strings.po
  resources/lib/demo.py
  resources/lib/monitor.py
  resources/lib/playbackmanager.py
  resources/lib/player.py
  resources/lib/playitem.py
  resources/lib/stillwatching.py
  resources/lib/upnext.py
  resources/settings.xml
  tests/xbmcgui.py
Labels: enhancement, testing

#222 Small fix
  resources/lib/stillwatching.py
  resources/lib/upnext.py
Labels: bug

#223 Updated german translation
  resources/language/resource.language.de_de/strings.po
Labels: translations

#217 Prepare for v1.1.3 release
  README.md
  addon.xml
Labels: release
