Repository im85288/service.upnext, pull requests merged in 2020-05, with the labels that each got.

#180 Hindi support
  resources/language/resource.language.in_hi/strings.po
Labels: translations

#183 Log data on JSON decode errors
  resources/lib/monitor.py
  tests/xbmcgui.py
Labels: enhancement

#185 Small fixes
  .github/workflows/addon-check.yml
  requirements.txt
  tests/xbmc.py
Labels: testing

#184 Avoid conflict with external players
  resources/lib/monitor.py
Labels: enhancement

#187 Add support for Addon setting types
  resources/lib/api.py
  resources/lib/monitor.py
  resources/lib/playbackmanager.py
  resources/lib/script.py
  resources/lib/state.py
  resources/lib/upnext.py
  resources/lib/utils.py
  resources/settings.xml
  tests/userdata/addon_settings.json
Labels: enhancement
